server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    # path for about view
    path('about/', views.about, name='about'),
    # path for contact us view
    path('contact/', views.contact, name='contact'),
    # path for registration
    path('registration_request/', views.registration, name='registration'),
    # path for login
    path('login/', views.login_request, name='login'),
    # path for logout
    path('logout/', views.logout_request, name='logout'),

    path('', views.get_dealerships, name='index'),

    # path for dealer reviews view
    path('dealer/<int:dealer_id>/', views.get_dealer_details, name='dealer_details'),
    # path for add a review view

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.
class CarMake(models.Model):
    name = models.CharField(max_length=50, primary_key=True)
    desc = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class CarModel(models.Model):
    name = models.CharField(max_length=50, primary_key=True)
    id = models.CharField(max_length=2)
    type = models.CharField(max_length=10)
    year = models.DateField(null=True)
    carmakes = models.ManyToManyField(CarMake)

    def __str__(self):
        return self.name

class CarDealer:

    def __init__(self, address, city, full_name, id, lat, long, short_name, st, zip):
        self.address = address
        self.city = city
        self.full_name = full_name
        self.id = id
        self.lat = lat
        self.long = long
        self.short_name = short_name
        self.st = st
        self.zip = zip

    def __str__(self):
        return "Dealer name: " + self.full_name

class DealerReview:

    def __init__(self, dealership, name, purchase, review, purchase_date, car_make, car_model, car_year, sentiment, id):
        self.dealership = dealership
        self.name = name
        self.purchase = purchase
        self.review = review
        self.purchase_date = purchase_date
        self.car_make = car_make
        self.car_model = car_model
        self.car_year = car_year
        self.sentiment = sentiment
        self.id = id

    def __str__(self):
        return "Dealer name: " + self.full_name

server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
# from .models import related models
# from .restapis import related methods
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json
from .restapis import get_dealers_from_cf, get_dealer_reviews_from_cf

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.


# Create an `about` view to render a static about page
# def about(request):
def about(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/about.html', context)

# Create a `contact` view to return a static contact page
#def contact(request):
def contact(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/contact.html', context)
# Create a `login_request` view to handle sign in request
# def login_request(request):
def login_request(request):
    context = {}
    if request.method == "POST":
        # Get username and password from request.POST dictionary
        username = request.POST['username']
        password = request.POST['psw']
        # Try to check if provide credential can be authenticated
        user = authenticate(username=username, password=password)
        if user is not None:
            # If user is valid, call login method to login current user
            login(request, user)
            return redirect('djangoapp:index')
        else:
            # If not, return to login page again
            return render(request, 'djangoapp/login.html', context)
    else:
        return render(request, 'djangoapp/login.html', context)

# Create a `logout_request` view to handle sign out request
# def logout_request(request):
def logout_request(request):
    context = {}
    logout(request)
    print("Log out the user `{}`".format(request.user.username))
    if request.method == "GET":
        return render(request, 'djangoapp/logout.html', context)


# Create a `registration_request` view to handle sign up request
# def registration_request(request):
def registration(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)
    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("djangoapp:index")
        else:
            context['message'] = "User already exists."
            return render(request, 'djangoapp/registration.html', context)



# Update the `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):
    if request.method == "GET":
        context = {}
        url = "https://b10aea74.us-east.apigw.appdomain.cloud/api/dealerships"
        dealerships = get_dealers_from_cf(url)
        dealer_names = ' '.join([dealer.short_name for dealer in dealerships])
        context["dealership_list"] = dealerships
        return render(request, 'djangoapp/index.html', context)


# Create a `get_dealer_details` view to render the reviews of a dealer
def get_dealer_details(request, dealer_id):
    if request.method == "GET":
        context = {}
        url = "https://b10aea74.us-east.apigw.appdomain.cloud/api/dealerships/{{dealer_id}}"
        dealerships = get_dealer_reviews_from_cf(url)
        dealer_reviews = ' '.join([dealer.review for dealer in dealerships])
        context["dealer_reviews"] = dealer_reviews
        return render(request, 'djangoapp/dealer_details.html', context)

# Create a `add_review` view to submit a review
def add_review(request, id):
    context = {}
    dealer_url = "https://b10aea74.us-east.apigw.appdomain.cloud/api/dealerships"
    dealer = get_dealer_by_id_from_cf(dealer_url, id=id)
    context["dealer"] = dealer
    if request.method == 'GET':
        # Get cars for the dealer
        cars = CarModel.objects.filter(id=id)
        context["cars"] = cars
        return render(request, 'djangoapp/add_review.html', context)
    elif request.method == 'POST':
        if request.user.is_authenticated:
            username = request.user.username
            payload = dict()
            car_id = request.POST["car"]
            car = CarModel.objects.get(pk=car_id)
            payload["time"] = datetime.utcnow().isoformat()
            payload["name"] = username
            payload["dealership"] = id
            payload["id"] = id
            payload["review"] = request.POST["content"]
            payload["purchase"] = False
            if "purchasecheck" in request.POST:
                if request.POST["purchasecheck"] == 'on':
                    payload["purchase"] = True
            payload["purchase_date"] = request.POST["purchasedate"]
            payload["car_make"] = car.make.name
            payload["car_model"] = car.name
            payload["car_year"] = int(car.year.strftime("%Y"))

            new_payload = {}
            new_payload["review"] = payload
            review_post_url = "https://b10aea74.us-east.apigw.appdomain.cloud/api/review/"
            post_request(review_post_url, new_payload, id=id)
        return redirect("djangoapp:dealer_details", id=id)

server/djangoapp/templates/djangoapp/about.html
{% extends "djangoapp/index.html" %}

{% block title %}About{% endblock %}

{% block content %}
<h1>
Welcome to Best Cars dealership, home to the best cars in North America. We sell domestic and imported cars at reasonable prices.
</h1>
{% endblock %}

server/djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>

</head>
    <body>


    </body>
</html>

server/djangoapp/templates/djangoapp/contact.html
{% extends "djangoapp/index.html" %}

{% block title %}Contact Us{% endblock %}

{% block content %}
<h1>Contact Us</h1>
<address>
Best Cars<br>
Some Street<br>
Some Town, NY<br>
(555)555-1234<br>
</address>


{% endblock %}

server/djangoapp/templates/djangoapp/dealer_details.html
{% extends "djangoapp/index.html" %}

{% block title %}Dealership Review{% endblock %}


{% block content %}
          {% if user.is_authenticated %}
          <a href="#">Add Review</a>
          {% endif %}
          <div class="card-columns">
            <!--{% for y in dealer_reviews %}
            <div class="card">
              {{y}}
            </div>
            {% endfor %}-->

          </div>
{% endblock %}

server/djangoapp/templates/djangoapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Dealership Review{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
</head>

    <body>
    <!--Add a nav bar here -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Dealership Review</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="/djangoapp/">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="/djangoapp/about">About</a>
          <a class="nav-item nav-link" href="/djangoapp/contact#">Contact</a>
        </div>
      </div>
      <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
               <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
               <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
               <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                  {% csrf_token %}
                  <div class="input-group">
                       <input type="text" class="form-control" placeholder="Username" name="username" >
                       <input type="password" class="form-control" placeholder="Password" name="psw" >
                       <button class="btn btn-primary" type="submit">Login</button>
                       <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                  </div>
               </form>
          </li>
          {% endif %}
      </ul>

    </nav>

    <!--Add a dealer table here -->
    {% block content %}
<table class="table" id="table" data-filter-control="true">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="dealer name">Dealer Name</th>
      <th data-field="city">City</th>
      <th data-field="address">Address</th>
      <th data-field="zip">Zip</th>
      <th data-field="state" data-filter-control="select">State</th>
  </tr>
</thead>
  {% for x in dealership_list %}
  <tr>
    <td>{{x.id}}</td>
<td><a href="{% url 'djangoapp:dealer_details' x.id%}">{{x.full_name}}</a></td>
<td>{{x.city}}</td>
<td>{{x.address}}</td>
<td>{{x.zip}}</td>
<td>{{x.st}}</td>
  </tr>
  {%endfor%}
</table>
    {% endblock %}
    </body>
<script>
$(function(){
  $('#table').bootstrapTable()
})
</script>
</html>

server/djangoapp/templates/djangoapp/login.html
{% extends "djangoapp/index.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<form action="{% url 'djangoapp:login' %}" method="post">
  {% csrf_token %}
  <div class="container"> <!--Style root div with .container class -->
    <h1>Login</h1>
    <div class="form-group"> <!--Style second div with .form-group class -->
      <label for="username"><b>User Name</b></label>
      <input id="username" class = "form-control" type="text" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
      <label for="psw"><b>Password</b></label>
      <input id="psw" class = "form-control" type="password"  placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
    </div>
    {% if message %}
      <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
        {{ message }}
      </div>
    {% endif %}
    <button class="btn btn-primary" type="submit">Login</button> <!--Style button with .btn and .btn-primary class -->
  </div>
</form>

{% endblock %}

server/djangoapp/templates/djangoapp/logout.html
{% extends "djangoapp/index.html" %}

{% block title %}logout{% endblock %}

{% block content %}
<h2>Logout</h2>


{% endblock %}

server/djangoapp/templates/djangoapp/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
    <body>
      <form action="{% url 'djangoapp:registration' %}" method="post">
    <div class="container"> <!--Style root div with .container class -->
      {% csrf_token %}
      <h1>Sign Up</h1>
      <hr>
      <div class="form-group"> <!--Style second div with .form-group class -->
          <label for="username"><b>User Name</b></label>
          <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
          <label for="firstname"><b>First Name</b></label>
          <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required> <!--Style input with .form-control class -->
          <label for="lastname"><b>Last Name</b></label>
          <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required> <!--Style input with .form-control class -->
          <label for="psw"><b>Password</b></label>
          <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
          {% if message %}
          <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
              {{ message }}
          </div>
          {% endif %}
          <button class="btn btn-primary" type="submit">Sign up</button> <!--Style button with .btn and .btn-primary class -->
      </div>
    </div>
  </form>
    </body>
</html>